<a href="https://colab.research.google.com/github/435wldms/essa/blob/main/20231109_%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

562-579

# 추천 시스템

**01 추천 시스템의 개요와 배경**
* 추천시스템은 사용자 자신도 좋아하는지 몰랐던 취향을 시스템이 발견하고 그에 맞는 콘텐츠를 추천해주기 때문에 사용자가 해당 사이트를 더 강하게 신뢰하게 되어 더 많은 추천 콘텐츠를 선택하고, 더 정확하고 다양한 결과를 얻을 수 있는 선순환 시스템을 구축하게 됨.

**온라인 스토어의 필수 요소, 추천 시스템**
* 너무 많은 상품 이미지, 카테고리, 메뉴 구성등으로 어려움을 겪는 사용자들에게 추천 시스템은 좋은 역할을 함
* 여러 데이터를 기반으로 추천 시스템은 친숙한 문구를 통해 사용자가 상품을 구매하도록 유혹


**추천 시스템의 유형**
* 추천 시스템의 종류: 콘텐츠 기반 필터링,협업 필터링, 잠재 요인 협업 필터링
* 초창기에는 콘텐츠 기반, 최근접 이웃 기반 협업 필터링이 주로 사용되었지만, 추천 시스템 경연 대회에서 행렬 분해 기법을 이용한 잠재 요인 협업 필터링 방식이 우승하면서 대부분 잠재요인 협업 필터링 기반 추천 시스템 적용
* 서비스하는 아이템에 따라 다양한 방식을 사용하지만 요즘에는 개인화 특성을 좀 더 강화하기 위해서 하이브리드 형식으로 콘텐츠 기반과 협업 기반을 적절히 결합해 사용하는 경우가 많음

**02 콘텐츠 기반 필터링 추천 시스템**
* 사용자가 특정한 아이템을 매우 선호하는 경우, 그 아이템과 비슷한 콘텐츠를 가진 다른 아이템을 추천하는 방식


**03 최근접 이웃 협업 필터링**
* 친구에게 물어보는 것과 유사한 방식으로 사용자가 아이템에 매긴 평점 정보나 상품 구매 이력과 같은 사용자 행동 양식만을 기반으로 추천을 수행하는 것이 협업 필터링 방식
* 주요 목표는 사용자-아이템 평점 매트릭스와 같은 축적된 사용자 행동 데이터를 기반으로 사용자가 아직 평가하지 않은 아이템을 예측 평가하는 것
* 협업 필터링 기반 추천 시스템: 최근접 이웃 방식, 잠재 요인 방식 (평점 행렬 데이터에만 의지해 추천 수행) -> 행은 개별 사용자, 열은 개별 아이템, 칸의 수치는 평점
* 원하는 정리된 행렬이 아니면 pivot_table()과 같은 함수를 이용해 사용자-아이템 평점 행렬 형태로 변경해야 함
* 사용자-아이템 평점 행렬은 많은 아이템을 열로 가지는 다차원 행렬, 평점을 매기는 경우가 많지 않으므로 희소 행렬인 특징
* 최근접 이웃 협업 필터링 (=메모리 협업 필터링) - 사용자 기반과 아이템 기반으로 구분
* 사용자 기반 최근접 이웃 방식은 '특정 사용자와 유사한 다른 사용자를 top-n으로 선정해' 이 top-n 사용자가 좋아하는 아이템을 추천하는 방식
* 아이템 기반 최근접 이웃 방식은 아이템이 가지는 속성과는 상관없이, 사용자들이 아이템을 좋아하는지/싫어하는지 '평가 척도가 유사한' 아이템을 추천하는 알고리즘
* 일반적으로 사용자 기반보다는 아이템 기반 협업 필터링이 정확도가 더 높음. (비슷한 영화를 좋아한다고 해서 사람들의 취향이 비슷하다고 판단하기는 어려운 경우가 많기 때문)
* 텍스트 분석에서 소개된 유사도 측정 방법인 코사인 유사도를 가장 많이 사용함 (피처 벡터화된 텍스트 데이터와 동일하게 다차원 희소 행렬의 특징을 가지기 때문)

**04 잠재 요인 협업 필터링**
* 사용자-아이템 평점 매트릭스 속에 숨어 있는 잠재 요인을 추출해 추천 예측을 할 수 있게 하는 기법
* 행렬 분해: 대규모 다차원 행렬을 svd와 같은 차원 감소 기법으로 분해하는 과정에서 잠재 요인을 추출
* 잠재 요인 협업 필터링은 사용자-아이템 평점 행렬 데이터만을 이용해 '잠재 요인'을 이끌어내는 것, 잠재 요인을 기반으로 다차원 희소행렬을 저차원 밀집 행렬의 사용자-잠재요인 / 아이템-잠재요인행렬의 전치행렬로 분해할 수 있음
* 분해된 행렬의 내적을 통해 새로운 예측 사용자-아이템 평점 행렬 데이터를 만들어 아직 평점을 부여하지 않은 아이템에 대한 예측 평점 생성


**행렬 분해의 이해**
* 다차원의 매트릭스를 저차원 매트릭스로 분해하는 기법, 대표적으로 svd, nmf 등
* m개의 사용자 n개의 아이템을 가진 평점 행렬 R을 K차원인 잠재요인을 이용해 MxK(P), KxN(Q)의 행렬로 분해
* R(u,i) = p(u) * q(i)t -> p의 u행, q의 i행 사용자의 벡터  => 방식으로 계산하여 값을 구하고 예측도 수행 가능
* 행렬 분해는 주로 svd 방식 사용 but null이 없어야 함 -> 확률적 경사 하강법이나 als 방식 이용

**확률적 경사 하강법을 이용한 행렬 분해**
* p와 q행렬로 계산된 예측 r 행렬 값이 실제 r 행렬 값과 가장 최소의 오류를 가질 수 있도록 반복적인 비용 함수 최적화를 통해 p와 q를 유추해내는 것
* p와 q를 임의의 값을 가진 행렬로 설정 -> p * q(t)를 계산해 r행렬을 계산하고 실제 행렬과의 오류 값 계산 -> 이 값을 최소화하기 위해 적절한 값으로 각각 업데이트를 반복
* 과적합을 피하기 위해 규제를 반영한 비용 함수를 적용

In [4]:
# SGD를 이용해 행렬 분해를 수행하는 과정
import numpy as np

# 원본 행렬 R 생성, 분해 행렬 P와 Q 초기화, 잠재 요인 차원 K는 3으로 설정.
R = np.array([[4, np.NaN,np.NaN,2,np.NaN ],
              [np.NaN, 5, np.NaN, 3,1],
              [np.NaN,np.NaN,3,4,4],
              [5,2,1,2,np.NaN]])
num_users, num_items = R.shape
K=3

# P와 Q 행렬의 크기를 지정하고 정규 분포를 가진 임의의 값으로 입력합니다.
np.random.seed(1)
P = np.random.normal(scale=1./K, size=(num_users,K))
Q = np.random.normal(scale=1./K, size=(num_items,K))

In [5]:
# 실제 R 행렬과 예측 행렬의 오차를 구하는 get_rmse() 함수 생성
# null이 아닌 행렬 값의 위치 인덱스를 추출해 이 인덱스에 있는 실제 행렬 값과 예측 행렬 값의 RMSE 계산
from sklearn.metrics import mean_squared_error

def get_rmse(R,P,Q,non_zeros):
  error=0
  # 두 개의 분해된 행렬 P와 Q.T의 내적으로 예측 R 행렬 생성
  full_pred_matrix = np.dot(P,Q.T)

  # 실제 R 행렬에서 널이 아닌 값의 위치 인덱스 추출해 실제 R 행렬과 예측 행렬의 RMSE 추출
  x_non_zero_ind = [non_zero[0] for non_zero in non_zeros]
  y_non_zero_ind = [non_zero[1] for non_zero in non_zeros]
  R_non_zeros = R[x_non_zero_ind, y_non_zero_ind]
  full_pred_matrix_non_zeros = full_pred_matrix[x_non_zero_ind, y_non_zero_ind]
  mse = mean_squared_error(R_non_zeros, full_pred_matrix_non_zeros)
  rmse = np.sqrt(mse)

  return rmse

In [8]:
# SGD 기반으로 행렬 분해 수행
# R>0인 행 위치, 열 위치, 값을 non_zeros 리스트에 저장.
non_zeros = [(i,j,R[i,j]) for i in range(num_users) for j in range(num_items) if R[i,j]>0]

steps=1000
learning_rate=0.01
r_lambda=0.01

# SGD 기법으로 P와 Q 매트릭스를 계속 업데이트.
for step in range(steps):
  for i, j, r in non_zeros:
    # 실제 값과 예측 값 차이인 오류 값 구함
    eij = r - np.dot(P[i,:], Q[j,:].T)
    # Regularization을 반영한 SGD 업데이트 공식 적용
    P[i,:] = P[i,:] + learning_rate*(eij*Q[j,:]- r_lambda*P[i,:])
    Q[j,:] = Q[j,:] + learning_rate*(eij*P[i,:]- r_lambda*Q[j,:])
    rmse = get_rmse(R,P,Q,non_zeros)
    if (step%50) ==0:
      print('### iteration step:', step, 'rmse:',rmse)


### iteration step: 0 rmse: 3.2475255402584495
### iteration step: 0 rmse: 3.2465908465596782
### iteration step: 0 rmse: 3.240001170538425
### iteration step: 0 rmse: 3.2381485790985485
### iteration step: 0 rmse: 3.2383355624029324
### iteration step: 0 rmse: 3.237066663018253
### iteration step: 0 rmse: 3.235237278782524
### iteration step: 0 rmse: 3.2334055187092163
### iteration step: 0 rmse: 3.228120562324444
### iteration step: 0 rmse: 3.22631720731668
### iteration step: 0 rmse: 3.226425162809075
### iteration step: 0 rmse: 3.225031693566006
### iteration step: 50 rmse: 0.492114962541484
### iteration step: 50 rmse: 0.49188671936595735
### iteration step: 50 rmse: 0.4908767627014268
### iteration step: 50 rmse: 0.490706148990846
### iteration step: 50 rmse: 0.49080798389226865
### iteration step: 50 rmse: 0.4901647116343035
### iteration step: 50 rmse: 0.49024508668575006
### iteration step: 50 rmse: 0.489756757805949
### iteration step: 50 rmse: 0.48218311207525344
### iterati

In [9]:
# 분해된 p,q 함수를 p*qT로 예측 행렬을 만들어 출력
pred_matrix = np.dot(P,Q.T)
print('예측 행렬: \n', np.round(pred_matrix,3))

예측 행렬: 
 [[3.99  0.804 1.334 2.002 1.714]
 [6.67  4.978 0.962 2.98  1.003]
 [6.843 0.408 2.987 3.977 3.986]
 [4.968 2.005 1.007 2.018 1.158]]


-> 널이 아닌 값은 비슷한 값으로, 널인 값은 새로운 예측값으로 채워짐