<a href="https://colab.research.google.com/github/435wldms/essa/blob/main/Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [37]:
np.__version__
np.show_config()

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

#### 3. Create a null vector of size 10 (★☆☆)

In [39]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [41]:
memory = np.array([1,2,3])
print("%d bytes" % (memory.size * memory.itemsize))

24 bytes


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [40]:
f = np.zeros(10)
f[4]=1
f

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [42]:
s = np.arange(10,50)
print(s)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [43]:
np.arange(10,50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
e = np.arange(9)
m_e = e.reshape(3,3)
m_e

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [44]:
n = np.array([1,2,0,0,4,0])
nonzero=n[n!=0]
print(nonzero)

[1 2 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [46]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [21]:
np.random.random((3,3,3))

array([[[0.93134784, 0.20494255, 0.8545529 ],
        [0.10529858, 0.10243067, 0.8544069 ],
        [0.91660574, 0.58543281, 0.58918702]],

       [[0.22112225, 0.84068627, 0.73881332],
        [0.52855896, 0.22760752, 0.50212308],
        [0.33187145, 0.98089675, 0.25384027]],

       [[0.67679232, 0.47996259, 0.99490101],
        [0.96643124, 0.45662504, 0.85792456],
        [0.69177986, 0.5460061 , 0.13904073]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [26]:
my_t = np.random.random((10,10))
min1=np.min(my_t)
max1=np.max(my_t)
print(min1,max1)

0.003396646852412033 0.9821243521436759


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [28]:
mean1=np.random.random((30))
mean2= np.mean(mean1)
mean2

0.4754015930583129

#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [47]:
array1=np.ones((10,10))
array1[1:-1,1:-1] = 0
print(array1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
# nan, False, False, nan, True , True

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [48]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [50]:
A = np.zeros((8,8),dtype=int)
for i in range(8):
    for j in range(8):
        if (i+j)%2==0:
            A[i][j]=2
print(A)

[[2 0 2 0 2 0 2 0]
 [0 2 0 2 0 2 0 2]
 [2 0 2 0 2 0 2 0]
 [0 2 0 2 0 2 0 2]
 [2 0 2 0 2 0 2 0]
 [0 2 0 2 0 2 0 2]
 [2 0 2 0 2 0 2 0]
 [0 2 0 2 0 2 0 2]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [35]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [54]:
a = np.random.random((5,5))
b = (a-np.mean(a))/ np.sqrt(a)
b

array([[-7.36721833e-02, -1.40309264e-01, -1.58377997e-01,
         3.59577882e-01, -9.68532596e-01],
       [-1.24387422e+00, -3.44034051e-01,  6.06193938e-02,
        -6.92962087e+01,  3.69732805e-03],
       [ 1.28507879e-01, -4.22884937e-01,  1.97690045e-01,
        -3.00220484e-01,  1.15791351e-02],
       [ 3.94530735e-01,  4.33192858e-01, -1.18391866e+01,
         2.83974935e-01,  3.35693084e-01],
       [ 1.31161363e-01,  3.32193299e-01,  4.26423407e-01,
         3.79116291e-01, -1.66864239e+00]])

#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [55]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-55-b9f1a6f5df9c>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [57]:
A = np.dot(np.ones((5,3)), np.ones((3,2)))
A

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [66]:
a = np.arange(10)
a[(a>3) & (a<=8)]*=-1
print(a)

[ 0  1  2  3 -4 -5 -6 -7 -8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [65]:
print(sum(range(5),-1))
from numpy import *

9


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z= np.arange(5)

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [64]:
np.array(0) / np.array(0)

<ipython-input-64-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [63]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 1

In [ ]:
# column 2

In [ ]:
# column 3