<a href="https://colab.research.google.com/github/435wldms/essa/blob/main/Numpy_exercises_%EC%B5%9C%EC%B5%9C%EC%A2%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
np.__version__
np.show_config()

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
memory = np.array([1,2,3])
print("%d bytes" % (memory.size * memory.itemsize))

24 bytes


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
f = np.zeros(10)
f[4]=1
f

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
s = np.arange(10,50)
print(s)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
np.arange(10,50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
e = np.arange(9)
m_e = e.reshape(3,3)
m_e

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
n = np.array([1,2,0,0,4,0])
nonzero=n[n!=0]
print(nonzero)

[1 2 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [4]:
np.random.random((3,3,3))

array([[[0.01803694, 0.6223971 , 0.23291266],
        [0.15067501, 0.3824975 , 0.67216584],
        [0.35371045, 0.62048481, 0.82034486]],

       [[0.07056496, 0.39797571, 0.21801032],
        [0.38694787, 0.7666084 , 0.07882511],
        [0.08666786, 0.88831273, 0.59554577]],

       [[0.84002372, 0.91658007, 0.92597381],
        [0.07143945, 0.65377977, 0.15092752],
        [0.29034647, 0.84400757, 0.64548455]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [5]:
x = np.random.random((10,10))
min=np.min(x)
max=np.max(x)
print(min,max)

0.00836592507299061 0.9976786093088472


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [6]:
x=np.random.random((30))
mean= np.mean(x)
mean

0.45854544557979376

#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [7]:
array=np.ones((10,10))
array[1:-1,1:-1] = 0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
# nan, False, False, nan, True , True

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [8]:
x = np.diag(1+np.arange(4), k = -1)
print (x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [9]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [10]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [12]:
x = np.random.random((5,5))
z = (x-np.mean(x))/ np.sqrt(x)
z

array([[-2.06638852, -0.84112716, -0.54338619,  0.30598745, -0.04022587],
       [-0.2112514 ,  0.33639756,  0.11063728, -0.47865091, -1.55428098],
       [ 0.45338425, -0.76766329, -3.4065602 ,  0.16680417, -3.78573746],
       [ 0.20992032, -0.0513759 ,  0.33964725,  0.28747161,  0.40544819],
       [ 0.35981162,  0.36600179,  0.083406  ,  0.27784951, -0.07409437]])

#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-55-b9f1a6f5df9c>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
A = np.dot(np.ones((5,3)), np.ones((3,2)))
A

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
a = np.arange(10)
a[(a>3) & (a<=8)]*=-1
print(a)

[ 0  1  2  3 -4 -5 -6 -7 -8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *

9


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z= np.arange(5)

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)

<ipython-input-64-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [ ]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

In [ ]:
import numpy as np

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
value = np.intersect1d(Z1,Z2)
print(Z1,Z2,value)

[3 1 7 6 8 0 6 4 4 2] [5 1 5 9 5 9 4 6 3 0] [0 1 3 4 6]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
#False

In [ ]:
np.sqrt(-1)

<ipython-input-7-597592b72a04>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)


nan

In [ ]:
np.emath.sqrt(-1)

1j

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [ ]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [ ]:
A=np.ones(3)*1
B=np.ones(3)*2
np.add(A,B, out =B)
np.negative(A, out=A)
np.divide(A,2, out=A)
np.multiply(A,B, out=A)
print(A)

[-1.5 -1.5 -1.5]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [ ]:
z = np.random.uniform(0,10,10)
a1 = z // 1
a2 = z - z % 1
print(a1,a2)

[7. 7. 1. 5. 2. 2. 9. 7. 4. 8.] [7. 7. 1. 5. 2. 2. 9. 7. 4. 8.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
z = np.zeros((5,5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
a= np.random.random(10)
print(a)
np.sort(a)

[0.55810438 0.75081492 0.68851895 0.66809359 0.30600687 0.76989182
 0.87116358 0.38783958 0.14509921 0.9748508 ]


array([0.14509921, 0.30600687, 0.38783958, 0.55810438, 0.66809359,
       0.68851895, 0.75081492, 0.76989182, 0.87116358, 0.9748508 ])


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
a=np.array_equal(A, B, equal_nan=False)

print(a)

True


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [ ]:
z = np.random.random((10, 2))
x, y = z[:,0],z[:,1] 
r = np.sqrt(x**2+y**2) 
p = np.arctan2(y,x) 
print(r)
print(p)

[1.04528333 0.74806324 0.79391737 0.76336955 0.87903848 0.84258627
 0.371968   0.71864645 0.1217191  0.15768796]
[0.99199391 0.31103903 1.35290572 0.54788714 0.43083882 1.31202968
 0.9664913  0.01168661 0.15292892 0.75443474]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [ ]:
z= np.random.random(10)
max=np.argmax(z)
print(z,max)

z[max]=0
print(z)

[0.97430258 0.74795075 0.78972956 0.95213264 0.51687238 0.01207433
 0.3525372  0.21590892 0.15384534 0.32344652] 0
[0.         0.74795075 0.78972956 0.95213264 0.51687238 0.01207433
 0.3525372  0.21590892 0.15384534 0.32344652]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print(v)

dis = np.abs(Z-v)
min_dis =np.argmin(dis)

print(dis, min_dis)

0.28677674189889757
[ 0.28677674  0.71322326  1.71322326  2.71322326  3.71322326  4.71322326
  5.71322326  6.71322326  7.71322326  8.71322326  9.71322326 10.71322326
 11.71322326 12.71322326 13.71322326 14.71322326 15.71322326 16.71322326
 17.71322326 18.71322326 19.71322326 20.71322326 21.71322326 22.71322326
 23.71322326 24.71322326 25.71322326 26.71322326 27.71322326 28.71322326
 29.71322326 30.71322326 31.71322326 32.71322326 33.71322326 34.71322326
 35.71322326 36.71322326 37.71322326 38.71322326 39.71322326 40.71322326
 41.71322326 42.71322326 43.71322326 44.71322326 45.71322326 46.71322326
 47.71322326 48.71322326 49.71322326 50.71322326 51.71322326 52.71322326
 53.71322326 54.71322326 55.71322326 56.71322326 57.71322326 58.71322326
 59.71322326 60.71322326 61.71322326 62.71322326 63.71322326 64.71322326
 65.71322326 66.71322326 67.71322326 68.71322326 69.71322326 70.71322326
 71.71322326 72.71322326 73.71322326 74.71322326 75.71322326 76.71322326
 77.71322326 78.71322326 79.713

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [ ]:
Z = np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
Z = np.arange(9).reshape(3,3)
for index in np.ndindex(Z.shape):
  print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [ ]:
n = 5
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),1)
print(Z)

[[0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)

[[8 8 6]
 [5 8 3]
 [9 6 2]]


In [ ]:
# column 1
Z[Z[:,0].argsort()]

array([[5, 8, 3],
       [8, 8, 6],
       [9, 6, 2]])

In [ ]:
# column 2
Z[Z[:,1].argsort()]

array([[9, 6, 2],
       [8, 8, 6],
       [5, 8, 3]])

In [ ]:
# column 3
Z[Z[:,2].argsort()]

array([[9, 6, 2],
       [5, 8, 3],
       [8, 8, 6]])