<a href="https://colab.research.google.com/github/435wldms/essa/blob/main/%EA%B3%BC%EC%A0%9C1_2014015_%EB%B0%95%EC%A7%80%EC%9D%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy
import pandas
import matplotlib.pyplot
import seaborn
from sklearn.model_selection import train_test_split

**- Numpy**

* numpy ndarray
>
>array 함수: 파이썬의 리스트와 같은 다양한 인자를 입력받아서 ndarray로 변환하는 기능을 수행
>
* ndarray의 shape 변수는 ndarray의 크기(행, 열의 개수)를 튜플 형태로 보여줌.


In [3]:
import numpy as np

In [3]:
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


* ndarray.dim = 차원 값 돌려줌

In [5]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


* ndarray의 데이터 타입: 숫자, 문자, 불 값 등 모두 가능하지만 같은 데이터 타입끼리만 가능함

In [6]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


* 데이터 유형이 서로 다른 리스트를 ndarray로 변경하면 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용함.

In [7]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3=[1,2,3.0]
array3 = np.array(list3)
print(array3,array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


* ndarray 내 데이터 값의 타입 변경 : astype() 이용

In [9]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


* ndarray를 편리하게 생성 - arange, zeros, ones
>
arange: range와 유사(0부터 함수인자값-1까지)
>
zeros: 모든 값을 0으로 채운 ndarray값을 반환
>
ones: 모든 값을 1로 채운 ndarray값을 반환
> 
data type을 정하지 않으면 default 값: float 형

In [10]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [11]:
zero_array = np.zeros((3,2),dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


* reshape: ndarray를 특정 차원 및 크기로 변환

In [4]:
array1 = np.arange(10)
print('array1:\n',array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [5]:
array1.reshape(4,3)
#error : 지정된 사이즈 변경 불가

ValueError: ignored

* reshape을 효율적으로 사용하는 경우: -1을 인자로 사용

In [6]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)
array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [7]:
array4 = array1.reshape(-1,4)
#error: 지정된 사이즈 변경 불가

ValueError: ignored

In [10]:
#reshape(-1.1)을 이용해 3차원을 2차원으로, 1차원을 2차원으로 변경
array1=np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d: \n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5: \n', array5.tolist())
print('array5 shape: ', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6: \n', array6.tolist())
print('array6 shape: ', array6.shape)

array3d: 
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5: 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape:  (8, 1)
array6: 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape:  (8, 1)


* ndarray의 데이터 세트 선택: 인덱싱
>
1. 특정한 데이터만 추출
>
2. 슬라이싱([시작:끝])
>
3. 팬시 인덱싱(리스트나 ndarray르 인덱스 집합을 지정하여 해당 위치의 인덱스에 해당하는 ndarray를 반환)
>
4. 불린 인덱싱(특정 조건에 해당하는지 여부를 가지는 집합을 인덱싱)

In [11]:
# 1. 특정 데이터만 추출
#1부터 9까지의 1차원 ndarray 생성
array1= np.arange(start=1, stop=10)
print('array1:', array1)
#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [12]:
print('맨 뒤의 값:',array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [13]:
#단일 인덱스를 이용해 ndarray 내의 데이터 값 수정
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


* 1차원 ndarray를 2차원으로 변환 후, [row, col]을 이용해 2차원에서 데이터 추출
>
row는 axis=0을, col은 axis=1을 의미

In [14]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값: ', array2d[0,0])
print('(row=0,col=1) index 가리키는 값: ', array2d[0,1])
print('(row=1,col=0) index 가리키는 값: ', array2d[1,0])
print('(row=2,col=2) index 가리키는 값: ', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값:  1
(row=0,col=1) index 가리키는 값:  2
(row=1,col=0) index 가리키는 값:  4
(row=2,col=2) index 가리키는 값:  9


In [15]:
# 2. 슬라이싱하기, 시작 ~ 종료 -1 까지 추출
array1 = np.arange(start=1, stop = 10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


시작, 종료 인덱스는 생략 가능
>
1. ':'기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0부터
>
2. ':'기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스까지
>
3. ':'기호 앞/뒤에 시작/종료 인덱스를 모두 생략하면 자동으로 모든 인덱스 추출

In [16]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [17]:
#2차원에서의 slicing
array1d = np.arange(start=1, stop=10) 
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2,0:2] \n', array2d[0:2,0:2])
print('array2d[1:3,0:3] \n', array2d[1:3,0:3])
print('array2d[1:3,:] \n', array2d[1:3,:])
print('array2d[:,:] \n', array2d[:,:])
print('array2d[:2,1:] \n', array2d[:2,1:])
print('array2d[:2,0] \n', array2d[:2,0])  # row만 슬라이싱 적용, col은 단일 인덱스

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2] 
 [[1 2]
 [4 5]]
array2d[1:3,0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:] 
 [[4 5 6]
 [7 8 9]]
array2d[:,:] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:] 
 [[2 3]
 [5 6]]
array2d[:2,0] 
 [1 4]


* 2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환
>
ex) array2d[0] -> row 축(axis=0)의 첫 번째 row를 반환

In [18]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [4]:
# 3. 팬시 인덱싱
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3=array2d[[0,1],2]
print('array2d[[0,1],2]=> ', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2]=>', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]]=> ', array5.tolist())

array2d[[0,1],2]=>  [3, 6]
array2d[[0,1], 0:2]=> [[1, 2], [4, 5]]
array2d[[0,1]]=>  [[1, 2, 3], [4, 5, 6]]


array3=array2d[[0,1],2] -> 인덱스 (0,2),(1,2)
>
array4 = array2d[[0,1], 0:2] -> 인덱스 (0,0:2),(1,0:2)
>
array5 = array2d[[0,1]] -> 인덱스 (0, :), (1,:)

In [5]:
# 4.불린 인덱싱
array1d = np.arange(start=1, stop=10)
#[]안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d>5]
print('array1d > 5 불린 인덱싱 결과 값: ', array3)

array1d > 5 불린 인덱싱 결과 값:  [6 7 8 9]


In [6]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

* 5보다 큰 데이터의 경우는 true값을 반환해 줌 -> true 값이 있는 위치 인덱스 값으로 자동 변환해 그 데이터들만 반환

In [7]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('array1d > 5 불린 인덱싱 결과 값: ', array3)

array1d > 5 불린 인덱싱 결과 값:  [6 7 8 9]


In [8]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과: ', array4)

일반 인덱스로 필터링 결과:  [6 7 8 9]


* 행렬의 정렬(sort, argsort)
>
* np.sort(): 원 행렬은 유지하고 원 행렬의 정렬된 
행렬을 반환 
>
vs
>
ndarray.sort() 원 행렬 자체를 정렬된 형태로 변환


In [9]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬: ', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬:  [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [10]:
#내림차순으로 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬: ',sort_array1_desc)

내림차순으로 정렬:  [9 5 3 1]


* 행렬이 2차원 이상인 경우에 axis 축 값을 설정해 로우, 칼럼 방향으로 정렬 수행 가능

In [11]:
array2d = np.array([[8,12],
                    [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('로우 방향으로 정렬: \n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬: \n',sort_array2d_axis1)

로우 방향으로 정렬: 
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬: 
 [[ 8 12]
 [ 1  7]]


* 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 np.argsort() 사용

In [12]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [13]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


* 넘파이의 ndarray는 RDBMS의 Table 칼럼이나 판다스 DataFrame의 칼럼과 같은 메타 데이터를 가질 수 없음

In [14]:
import numpy as np
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순으로 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순으로 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


* 선형대수 연산 (행렬 내적과 전치 행렬 구하기)
>
:행렬의 내적= 행렬의 곱, np.dot(A,B)로 표현

In [15]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])

dot_product = np.dot(A,B)
print('행렬 내적 결과 \n', dot_product)

행렬 내적 결과 
 [[ 58  64]
 [139 154]]


: 전치 행렬 = 원 행렬에서 행과 열 위치를 교환한 원소로 구성된 행렬

In [16]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬 \n', transpose_mat)

A의 전치 행렬 
 [[1 3]
 [2 4]]
